# Generated by Django 4.2 on 2023-04-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='influencer',
            table='influencers',
        ),
    ]
