# Generated by Django 4.2 on 2023-04-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('influencers', '0002_alter_influencer_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='influencer',
            name='tags',
            field=models.ManyToManyField(related_name='influencers', to='posts.tag'),
        ),
    ]
