# Generated by Django 4.2 on 2023-04-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_delete_tag_influencer_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='influencer',
            name='tags',
            field=models.ManyToManyField(related_name='influencers', to='influencers.tag'),
        ),
    ]
